type ChatMessage = {
  role: "system" | "user" | "assistant";
  content: string;
};

type RequestBody = {
  messages?: ChatMessage[];
  maxTokens?: number;
  temperature?: number;
};

const corsHeaders = {
  "Content-Type": "application/json",
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers": "content-type",
  "Access-Control-Allow-Methods": "POST,OPTIONS",
};

const json = (body: unknown, status = 200) =>
  new Response(JSON.stringify(body), {
    status,
    headers: corsHeaders,
  });

export async function OPTIONS() {
  return json({});
}

export async function POST(request: Request) {
  const apiKey = process.env.OPENAI_API_KEY;
  const model = process.env.OPENAI_MODEL || "gpt-4o-mini";

  if (!apiKey) {
    return json({ error: "OPENAI_API_KEY is not configured on the server." }, 500);
  }

  try {
    const body = (await request.json()) as RequestBody;
    const messages = Array.isArray(body.messages) ? body.messages : [];

    if (messages.length === 0) {
      return json({ error: "messages are required" }, 400);
    }

    const response = await fetch("https://api.openai.com/v1/chat/completions", {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        Authorization: `Bearer ${apiKey}`,
      },
      body: JSON.stringify({
        model,
        messages,
        max_tokens: typeof body.maxTokens === "number" ? body.maxTokens : 256,
        temperature: typeof body.temperature === "number" ? body.temperature : 0.9,
      }),
    });

    if (!response.ok) {
      const errorText = await response.text();
      return json(
        {
          error: `OpenAI API error: ${response.status} ${response.statusText}`,
          details: errorText,
        },
        response.status,
      );
    }

    const result = await response.json();
    const content = result?.choices?.[0]?.message?.content?.trim();

    if (!content) {
      return json({ error: "No response generated by OpenAI." }, 502);
    }

    return json({ content });
  } catch (error) {
    return json(
      {
        error: error instanceof Error ? error.message : "Unknown server error",
      },
      500,
    );
  }
}
